p5/sketch/events.py

Fixes #16 .
Pyglet returns cursor values which my not be in the range of scren size. Hence I have constraint the cursor values to the size of sketch

Set range limit on mouse_x and mouse_y values

---

p5/pmath/vector.py

Fixes #18 .
Replaced all `@` operator with `np.dot` since `@` operator was introduced from python3.5. 
There are still some issues while running the code:
```python 
from p5 import *
File "/Users/arihantparsoya/Documents/p5/p5/__init__.py", line 19, in <module>
from .sketch import *
File "/Users/arihantparsoya/Documents/p5/p5/sketch/__init__.py", line 19, in <module>
from .base import *
File "/Users/arihantparsoya/Documents/p5/p5/sketch/base.py", line 29, in <module>
from ..opengl import renderer
File "/Users/arihantparsoya/Documents/p5/p5/opengl/__init__.py", line 19, in <module>
from .renderer import *
File "/Users/arihantparsoya/Documents/p5/p5/opengl/renderer.py", line 33, in <module>
from ..pmath import matrix
File "/Users/arihantparsoya/Documents/p5/p5/pmath/__init__.py", line 22, …
```

Replaced @ with np.dot()

---

p5/pmath/vector.py

Fixes #37.
Added test condition in line 376 to raise ValueError when magnitude of vector is 0.
```python 
>>> from p5 import *
>>> x = Vector(0, 0)
>>> print(x.magnitude)
0.0
>>> x.normalize()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/arihantparsoya/Documents/p5/p5/pmath/vector.py", line 368, in normalize
raise ValueError('Cannot normalize vector with magnitude 0')
ValueError: Cannot normalize vector having magnitude 0
```

raise ValueError when Magnitude of Vector is 0

---

p5/pmath/curves.py

Simple fix for this bug so the package is backwards compatible.

fix bug #23: Tuple unpacking incompatible with Python 3.4 and less

---

p5/opengl/renderer.py
p5/sketch/base.py
requirements.txt

This also includes the framerate fix by @parsoyaarihant.

Fixes retina issues on the mac

---

p5/core/color.py

Stumbled across this issue recently using HSB color mode with an alpha value. Figured it was a rare enough of a situation that no one had caught the typo yet and it was an easy fix.

Fix typo on HSB mode with alpha

---

p5/sketch/base.py

To fix issue #88 
Error is in the following snippet of base.py
```python
if self.looping or self.redraw:
builtins.frame_count += 1
if not self.setup_done:
self.setup_method()
self.setup_done = True
self.show(visible=True)
self.redraw = True
self.looping = False
else:
self.looping = True
self.draw_method()
self.redraw = False
```
The error occurs because `self.looping` is controlled entirely by this block. Regardless of no_loop calls,
1) initially, `looping` is True (as no user code has been executed)
2) After the setup is called (no matter what happens to looping within the user setup), the block forces redraw to True and looping to False.
3) The next run through of the block sets looping to True initially. Note that if `no_loop()` was in `draw()`, it would be modified now, after setting …

Fix #88: no_loop doesn't work in setup

---

p5/core/attribs.py
p5/core/structure.py
p5/sketch/base.py
p5/sketch/renderer.py

Please check issue #60 for analysis on the issue.
Two changes made:
1) Function `background()` now returns the color if color is changed as expected
2) Function `background()` now permanently sets the renderer color to the new color. Note that this means that the behavior of the function is now inconsistent! Images can only be set in draw(), due to the mechanics of the renderer, while background color can be set from either draw() or setup().
I shall soon change the renderer to support images as backgrounds in setup() too.
Edit:
**Changed the renderer to be consistent with the color**
In the latest commit, both images and colors can be used in setup and draw.
This has been achieved by simply mimicking the background() function for images, minus checking validity, in the renderer's clear …

Fix issue 60: background() doesn't work in setup.

---

docs/guides/for-processing-users.rst

[Event System](https://p5.readthedocs.io/en/latest/guides/for-processing-users.html#event-system) example was calling event.key() instead of referencing the attribute event.key.

Fix typo in Processing user guide: event.key() to event.key

---

p5/core/font.py
p5/core/primitives.py

improved **text()**.
Instead of using width and height of the sketch, it uses proper boundaries form getsize() method of the font object. So _image_mode('CENTER')_ can be used without any problems.

Text patch 1

---

docs/tutorials/interactivity.rst

Hi!
the Draw a line from the previous mouse position example was broken.
I'm really like p5 so I planning to contribute for the documentation, fixing broken examples.
If you allow me of course
thanks for all your work!!

fix Draw a line previous mouse position example

---

docs/examples/transform/arm.rst

According to the documentation [here](https://p5.readthedocs.io/en/latest/guides/for-processing-users.html), `push_matrix` is a context manager and `pop_matrix` does not exist. In reality, `pop_matrix` exists but seems to do nothing according to the [source](https://github.com/p5py/p5/blob/1b233fdd59f19e97341e5cfb75bccb821ff79eab/p5/core/transforms.py#L41).
While a future PR is probably needed to clean up the implementation of the API, this PR removes the extraneous pop_matrix() call in the arm example code.

[DOC] Remove extra pop_matrix() call in arm example

---

p5/sketch/base.py

In the base.py frame_count was incremented without checking whether or not looping is set to true or false
Draw() was called again because there was no check to see if looping is false and redraw is true, then don't call draw()
Fixed it by putting a elif not self.looping : pass in the if else statements, 
You can test to see if everything and frame_count are working fine by putting print(frame_count) in base.py at various positions in the code

Closes #158 draw() being called multiple times and frame_count was incremented in wrong manner

---

p5/sketch/base.py

Closes #175 
#158 had problem of draw() being called two times if we use no_loop() inside draw() function, which was fixed by a PR by me but it led to #175, that is no_loop() when used in setup() don't call draw() once, as per Processing original documentation
This PR calls draw() once when used in setup() and don't call draw() again if no_loop() is used in draw() again, also I have tested the frame_count for each call and frame_count is being incremented as described by @jeremydouglass  in #162 comments,  
The issue #158 and #162 is taken care by this PR , I have tested the code for loop(), no_loop(), redraw() for both in setup() and draw() functions and some other codes from examples of p5 
But you can test it for some other scenarios too :)
PS : size() when used in setup() along with …

Correct implementation of no_loop()

---

docs/tutorials/pshape.rst

[typo in Pshape tutorial](https://p5.readthedocs.io/en/latest/tutorials/pshape.html#many-pshapes)
typo was: endShape("CLOSE").
Changed to correct syntax: end_shape("CLOSE")

Fixed typo in PShape tutorial

---

p5/core/primitives.py
p5/core/shape.py
p5/core/tess.py
p5/sketch/renderer2d.py

This PR decouples most of the OpenGL specific rendering logic from PShape, making it easier to write different backends.

Move 2D rendering from PShape to renderer2d

---

p5/sketch/openglrenderer.py
p5/sketch/renderer2d.py
p5/sketch/renderer3d.py

OpenGLRenderer is an abstract class that contains some of the common logic shared by the renderers that use vispy/opengl. It cannot be instantiated directly and is inherited by both Renderer2D and Renderer3D.

Abstract common rendering logic in OpenGLRenderer

---

p5/core/vertex.py

Unlike `end_shape`, `end_contour` does not have an optional parameter `'CLOSE'`. Therefore, the default behavior should be closing the contour automatically.
Fixes #195

Close contour automatically

---

p5/core/__init__.py
p5/core/material.py
p5/core/p5.py
p5/sketch/base.py
p5/sketch/openglrenderer.py
p5/sketch/renderer3d.py
p5/sketch/shaders/normal.frag
p5/sketch/shaders/normal.vert
p5/sketch/shaders3d.py
p5/sketch/util.py

Implements `normal_shader` that colors fragments based on the surface normal of a 3D model.
Sample:
```python
from p5 import *
def setup():
size(720, 400)
normal_material()
def draw():
background(205, 102, 94)
rotate_x(frame_count * 0.01)
rotate_y(frame_count * 0.01)
cone(200, 400)
if __name__ == '__main__':
run(mode='P3D')
```

Implement `normal_shader`

---

p5/core/geometry.py
p5/core/material.py
p5/core/shape.py
p5/core/structure.py
p5/sketch/light.py
p5/sketch/renderer3d.py

Implements `basic_material`. More importantly, shader type is no longer a global state within `renderer3d`. This means we can have objects with different materials being rendered in the same frame.
Example:
```python
from p5 import *
def setup():
size(720, 400)
def draw():
background(205, 102, 94)
normal_material()
cone(200, 400)
translate(200, 0, 0)
rotate_x(radians(180))
basic_material(155, 184, 48)
cone(200, 400)
if __name__ == '__main__':
run(mode='P3D')
```

Implement basic_material

---

p5/core/transforms.py

This PR fixes the following:
1. Despite the documentation string saying that `camera` can take empty arguments, doing so causes an error.
2. The default camera described in the documentation string of `camera` is different from what is acutally used by default at https://github.com/p5py/p5/blob/30adfda08cf95d3ceded511bd213f0b8d5c5d266/p5/sketch/userspace.py#L190-L193

Add default arguments for camera

---

p5/core/shape.py
p5/core/transforms.py

The intended behavior was to scale sy and sz the same about as sx, if sx was the only variable not None. `not 0` returns True in python. That is why `scale(0, 1)` worked but `scale(1, 0)` didn't.

Fixed issue #183

---

docs/examples/form/triangle strip.rst
docs/examples/input/clock.rst
p5/core/constants.py
p5/core/vertex.py
profiling/custom_shapes2.py
profiling/triangle_strip.py

Now instead of calling `begin_shape("TRIANGLE")`, one can use `begin_shape(TRIANGLE)`, which is more consistent compared to other processing dialects.

Create global variables for enum SType

---

p5/core/color.py
p5/core/light.py
p5/core/material.py

Colors in OpenGL are on a scale of 0.0 to 1.0, which is different from
the scale of 0.0 to 255.0 that p5py typically uses. This PR implements
a new normalized_rgb method in Color and uses it to preprocess colors
in 3D APIs.

Normalize colors in 3D mode

---

docs/reference/shape.rst
p5/core/primitives.py
profiling/arcs.py

Partially addresses #130
New signatures:
* `line(x1, y1, x2, y2)`
* `line(x1, y1, z1, x2, y2, z2)`
* `ellipse(a, b, c, d, mode=None)`
* `circle(x, y, radius, mode=None)`
* `arc(x, y, width, height, start_angle, stop_angle, mode=None, ellipse_mode=None)`

Add additional signatures for `line`, `circle`, `ellipse`, and `arc`

---

profiling/README.md
profiling/begin_contour.py
profiling/main.sh
profiling/spinning-cone.py
profiling/tetrahedron.py

Adds more sample scenes in the `profiling` folder.
Also includes a simple bash harness to run all the scenes because the previous python one does not always work possibly due to some global state being preserved between scenes.

Add more sample scenes to profile

---

.github/workflows/pylint.yml

@parsoyaarihant 
This should work, no module error was there in pylint occurred because we passed filenames instead of the whole path. So pylint was searching for the file only in the current directory.
Pylint job now builds on PRs as well as pushes.

pylint now runs on PRs

---

p5/core/image.py

`_texture` property now returns the data of the image instead of a `gloo.Texture2D` object. Texture objects are now created in the renderer itself.

Refactored image.py to support different renderers

---

p5/core/primitives.py
p5/core/primitives3d.py
p5/core/vertex.py
p5/sketch/Vispy2DRenderer/renderer2d.py

Related to #214 
`end_shape` now calls `p5.renderer.shape()` and passes the required data instead of returning a `PShape` obejct and using `@draw_on_return`

Refactor begin_shape & end_shape APIs to support multiple renderers

---

p5/sketch/Vispy2DRenderer/base.py

There is no need to add `_save_fname_num` to the image name. Images are saved by the default name or by the `filename` passed.

make save() consistent with processing

---

p5/sketch/Vispy2DRenderer/openglrenderer.py

This is how I resolved #307. Let me know if it makes any sense.

Fix vertex transformation in 2D renderer

---

.github/workflows/pylint.yml

The newest dependabot commit is failing pylint because `Module 'builtins' has no 'start_time' member`.
Running pylint on the whole package will hopefully give pylint enough context to recognize `start_time`.

Enable pylint for the entire p5 package

---

p5/sketch/Vispy2DRenderer/base.py
p5/sketch/userspace.py

Fixes #150 and additionally prevents a SystemExit exception being thrown/reported that is anyways ignored.
`p5.exit()` documentation mentions that it forwards args
to the builtin `exit()`, so do that instead of calling
the non-existing `p5.core.p5.exit()` function. (Or prevent
a recursive call that by exit ended up calling a
non-existant function.
Do not call `p5.exit()` in on_close: exit() will throw a SystemExit
exception which will be cought by vispy, reported and ignored.
Since the windows has gone away we only need to quit the
running application for a normal exit.

Fix exceptions shown when closing canvas

---

.github/workflows/pylint.yml
.github/workflows/pytest.yml
.github/workflows/sanityTesting.yml

On trigger exisiting Github Actions on PR against master or pushes in master.
This avoids the problem of the actions being run twice in a new PR.

Prevent gh-action from running twice on new PR

---

p5/sketch/Vispy2DRenderer/openglrenderer.py

As @tushar5526 discovered in #318, #308 broke the 3D pipeline, so it was temporarily reverted.
The problem is that the return value of `_transform_vertices` is not of type `np.array` when some functions expected it to be. This change fixes that while also rewriting the logic to use numpy native functions so it's more efficient.

Reapply #308 but return np.array instead of list

---

docs/install.rst

The minimum requiremnt is now 3.6. Closes #272.

Update minimum python version in documentation

---

.github/workflows/pylint.yml
.github/workflows/pytest.yml
.github/workflows/sanityTesting.yml
setup.py

Thanks to @jeremydouglass who spotted that the automated tests use a python version higher than the minimally supported one, this PR updates the tests to use Python 3.6.

Update minimum python version in tests

---

p5/sketch/Vispy2DRenderer/base.py
p5/sketch/Vispy2DRenderer/openglrenderer.py
p5/sketch/Vispy2DRenderer/renderer2d.py
p5/sketch/Vispy3DRenderer/renderer3d.py

Merge `initialize_renderer` with `__init__` for the renderer classes, since in the current implementation there's no information needed by `initialize_renderer` that's not available at the time of `__init__`.
Also fixes #340 and #333 since `texture_prog` now exists when `_on_resize` is called.

Move contents of initialize_renderer to __init__

---

docs/examples/structure/width and height.rst

fix of issue 'Documentation: Wrong image in Width and Height example #328'
Update the js canvas rendering to the width and height example

Fixed example of Width and height.

---

MANIFEST.in

The build was failing due to `requirements.txt` not being found. We had to manually include it in the `MANIFEST.in`
Both `tar ball` and `wheels` are building fine now

Update MANIFEST to include requirements.txt and fix the name of LICENSE file

---

p5/core/attribs.py
p5/core/constants.py
p5/core/image.py
p5/sketch/Skia2DRenderer/renderer2d.py
p5/sketch/Vispy2DRenderer/openglrenderer.py
p5/sketch/Vispy2DRenderer/renderer2d.py

Refactored image.py to use constants instead of strings

Bug fix: image() had wrong args parsing logic

---

p5/sketch/Skia2DRenderer/base.py
p5/sketch/Skia2DRenderer/renderer2d.py

Always use frame buffer size to create a skia surface to handle retina displays as well, this function will also serve as a utility function for PGraphics object so we need 'size' as well, as window is None in that case.

Use framebuffer size to create surface for retina displays

---

docs/reference/graphics.rst
docs/reference/index.rst
docs/reference/input.rst
p5/core/__init__.py
p5/core/font.py
p5/core/graphics.py
p5/core/image.py
p5/sketch/Skia2DRenderer/graphics.py
p5/sketch/Skia2DRenderer/image.py
p5/sketch/Skia2DRenderer/renderer2d.py
p5/sketch/Vispy2DRenderer/renderer2d.py

Related to #386 
The basic design of the Graphics object is like following. 
Graphics is declared as an empty abstract class. In case other renderers, have their own implementations of it. Almost each Processing API is also a method of `Graphics` object so I skipped defining abstract methods for each of them. As that would be too much redundant code and time-consuming. 
In the skia implementation, I am creating a new Renderer, canvas, surface, path and paint for each graphics object.
Then the methods are `binded` to the Graphics objects in a kind of unconventional way, but it works properly. 
The major scope of improvement here is to use a GPU-backed surface for smoother rendering. I need to dig more into how `glfw` contexts work and how can I create an offscreen context for surfaces. …

Add support to draw to an off screen buffer 

---

.github/workflows/blackFormatter.yml

Ref to Issue: #358 
I added a Github action which Runs on After a PR merge and Check if it is formatted with PEP standard and Formatted it with black formatter, and Make a PR with formatted code.

Added code formatting using black through a Github Action

---

docs/examples/index.rst
docs/examples/structure/create graphics.rst

Related to #386 
Added examples to use create_grphics in skia

Add examples for create_graphics

---

.github/workflows/pylint.yml
.github/workflows/pytest.yml
.github/workflows/sanityTesting.yml
requirements.txt

Closes #396
I think using the latest version of NumPy available for that specific python version would work fine instead of a specific version for all python versions. 
PyOpenGl's 3.1.6 works well on Ubuntu. Its need to be tested for windows and mac

Update requirements for 3.10

---

p5/sketch/userspace.py

The current code checks if "setup" is defined by the user before loading "preload". I suspect this is a simple copy-paste mistake from a couple of lines later, where the code checks if "setup" is defined before loading "setup".
This is a tiny fix.

Check is user has defined preload before use

---

p5/sketch/Skia2DRenderer/base.py
p5/sketch/userspace.py

This is a partial "fix" for #419 particularly for Skia Renderer. Related to #420
What I found tracing the calls are following:
- This issue is due to how `GLFW` handles `window resize events`.
- Whenever a glfw window is resized by `size()` or manually by the user, it triggers a window resize event in the `glfw event queue`, this event is inherently asynchronous, so this does not take place instantly, but when it does, a callback function is called. The callback function is assigned by [self.assign_callbacks()](https://github.com/p5py/p5/blob/4c63a4f72785d084f9dffe2ee99fe37a60fe373d/p5/sketch/Skia2DRenderer/base.py#L158) in the `start()` of SkiaSketch.
- We assign [frame_buffer_resize_callback_handler()](https://github.com/p5py/p5/blob/4c63a4f72785d084f9dffe2ee99fe37a60fe373d/p5/sketch/Ski …

Fix for unordinary behavior of size() in setup() for skia

---

docs/guides/vscode.rst
p5/core/primitives.py

Fixing issue #438 
Wrong unpacking of arguments for CORNERS mode.
Now supports both:
```
rectMode(CORNERS)
rect(100, 100, 200, 200)
```
and
```
rectMode(CORNERS)
rect((100, 100), 200, 200)
```
Example from the bug issue:

fix args unpacking for corners mode

---

p5/sketch/Skia2DRenderer/base.py
p5/sketch/Skia2DRenderer/handlers.py
p5/sketch/Skia2DRenderer/renderer2d.py
p5/sketch/userspace.py
requirements.txt

Realted to #424 #425
The jittery behaviour and errors with skia were due to wrong rendering logic. GLFW uses a double buffer swapping technique to render graphics and our logic was only running the new commands and the previous state was getting lost after buffer swaps. 
Currently did a hacky solution to fix it for now (tested on MacOS)
- We are currently storing the state of `surface` in an image before flushing and swapping the buffers. The state is then restored before the start of the next frame. 
- Another solution would be to mimic all the `path` in Canvas, which I don't think is easy to do with the current code structure. 
TODO: to switch to using `bitmap` or `pixmap` to store state
This PR also fixes the errors of wrong mouse position in retina displays on MAC.

fix jitter behaviour of skia due to double buffers swapping
