- README.rst
> added link to landing page of p5py documentation

- requirements.txt
- setup.py
add triangle to install dependencies as per #118
> add triangle to requirements.txt, setup.py

- p5/core/font.py
- p5/core/primitives.py
fixed the values for *dim* and *center* for creating *arc* object when *ellipse_mode* is set to *CORNER*
> Fixed CORNER mode for drawing arc

- p5/pmath/vector.py
Like this: `self.acc = (mouse - self.pos).normalize()`
Addresses #86
> allow chaining "normalize()" after +/- operations

- p5/core/constants.py
- p5/core/primitives3d.py
- p5/sketch/renderer3d.py
This PR consists two parts:
1. fix depth check
2. fix z-fighting
For more details, see #152
> Fix depth check in 3D mode

- docs/examples/color/color variables.rst
Old tutorial did not work. It also didn't match the image shown. I fixed the code to match the image. Also, I changed the name from "inside", "middle" and "outside" since these names are nonsense.
> Example does not work

- p5/sketch/renderer2d.py
Adds checks for the number of vertices in the renderer.
> Implement _check_shape

- p5/core/shape.py
This PR implements PShape edit functionality for the new rendering pipeline.
> Implement edit mode for PShape

- p5/core/light.py
- p5/core/material.py
- p5/sketch/renderer3d.py
- p5/sketch/shaders/3d/phong.frag
Methods included in this PR:
* `ambient(r, g, b)`
* `emissive(r,g,b)/diffuse(r, g, b)`
* `shininess(p)`
* `specular(r, g, b)`
* `light_falloff(constant, linear, quadratic)`
* `light_specular(r, g, b)`
> Implement various lighting APIs

- CONTRIBUTING.rst
https://join.slack.com/t/p5py/shared_invite/zt-e8mxhses-b2Vqc~zcU_kC5vCnJqrFxA  : Added this slack invite link in contribution.rst.
> Added slack link in contribution.rst

- p5/core/font.py
> Change nor to not

- p5/core/light.py
- p5/core/material.py
- p5/sketch/util.py
The Color class imposes an upper bound to colors, which constrains
the maximum intensity of the lights. To offer users more freedom, a
separate scale_colors function was implemented that allows color channels
to go beyond 255.
> Implement scale_colors

- docs/examples/3d/blinn_phong.rst
- docs/examples/index.rst
> Add example on Blinn Phong material

- docs/reference/index.rst
- docs/reference/io.rst
- p5/__init__.py
- p5/io/__init__.py
- p5/io/http.py
- test.py
Regarding [Issue](https://github.com/p5py/p5/issues/244)
Added  Synchronous versions of **http_get()** and **http_post()**
Please let me know about any changes, and where should I update the documentation and examples.
Thank you. :)
> Fixes Issue #244

- docs/reference/image.rst
- docs/reference/shape.rst
- docs/reference/transform.rst
- docs/reference/typography.rst
- p5/core/font.py
- p5/core/image.py
- p5/core/primitives.py
- p5/core/transforms.py
- p5/core/vertex.py
- p5/pmath/curves.py
- p5/pmath/tests/test_curves.py
Partially addresses #130
New signatures:
* `image(img, x, y)`
* `image(img, x, y, w, h)`
* `triangle(x1, y1, x2, y2, x3, y3)`
* `quad(x1, y1, x2, y2, x3, y3, x4, y4)`
* `rect(x, y, w, h)`
* `square(x, y, side_length)`
* `bezier(x1, y1, x2, y2, x3, y3, x4, y4)`
* `bezier(x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, y4, z4)`
* `curve(x1, y1, x2, y2, x3, y3, x4, y4)`
* `curve(x1, y1, z1, x2, y2, z2, x3, y3, z3, x4, y4, z4)`
* `camera(position_x, position_y, position_z, target_x, target_y, target_z, up_x, up_y, up_z)`
* `camera(position, target_position, up_vector)`
* `text(text_string, x, y)`
* `text(text_string, x, y, z)`
Following functions can now take floats and tuples of arbitrary length
* `bezier_point`
* `bezier_tangent`
* `curve_point`
* `curve_tangent`
* `quadratic_point`
> Add additional signatures PT2

- p5/core/attribs.py
- p5/core/constants.py
- p5/core/primitives.py
- p5/core/svg.py
- p5/sketch/openglrenderer.py
- p5/sketch/renderer2d.py
point() now works!
Fixes #161 
Fixes #238 
Fixes #186
> Fix point()

- p5/pmath/utils.py
`fract` was missing in math.py
> added fract API in calculations

- docs/tutorials/coordinate system and shapes.rst
- docs/tutorials/interactivity.rst
- docs/tutorials/typography.rst
**From Coordinate System and Shapes Tutorial:**
- fixed the "coordinate system and shapes" example at the end of the tutorial so now works as intended
**From Interactivity Tutorial:** 
- fixed the "Mouse Data" examples print x and y mouse position
- fixed some text format problems in "Interactivity" tutorial
- in "Keyboard data" fixed the angle example of interactivity tutorial, added ord() and str() methods
- in "Coded keys" example is not necessary define "y" value as 35 outside def
- in "Mouse events" example fixed the "mouse_moved()" and "mouse_dragged()" example
**From Typography Tutorial:**
- in "Vector Fonts" example fixed text format and change "textFont()" to "text_font()"
- in "Vector Fonts" in ...To use two fonts added global and deleted unnecessary text_font
- in "Vector …
> More tutorials examples fixed

- docs/reference/io.rst
> fixed docs error

- docs/reference/structure.rst
- docs/reference/transform.rst
- p5/core/attribs.py
- p5/core/font.py
- p5/core/geometry.py
- p5/core/image.py
- p5/core/material.py
- p5/core/primitives.py
- p5/core/shape.py
- p5/core/structure.py
- p5/core/transforms.py
- p5/core/vertex.py
- p5/sketch/openglrenderer.py
- p5/sketch/renderer2d.py
- p5/sketch/renderer3d.py
> Support pop syntax

- docs/reference/data.rst
- docs/reference/index.rst
- p5/__init__.py
- p5/data/__init__.py
- p5/data/local_storage.py
#258 
Will be adding docs later.
> added local Storage module

- requirements.txt
- setup.py
> Move all requirements to requirements.txt

- p5/data/tests/test_data.py
Added tests for storage module. 
Feedbacks are welcomed as I haven't wrote tests before.
Thanks :)
> added tests for storage module

- docs/examples/IO/GET.rst
- docs/examples/IO/POST.rst
- docs/examples/index.rst
Regarding issue [Add examples for IO Module #277](https://github.com/p5py/p5/issues/277)
> examples for IO

- .github/workflows/greetings.yml
Followed [this](https://github.com/actions/first-interaction/issues/10)
Greeting message when someone creates their new PR.
Failed case #282 
It works [test link](https://github.com/tushar5526/p5/pull/7)
> fix greeting message on PRs

- p5/core/__init__.py
- p5/core/api.py
- p5/core/color.py
- p5/core/primitives.py
- p5/data/__init__.py
- p5/data/api.py
- p5/io/__init__.py
- p5/io/api.py
- p5/io/local_data.py
- p5/pmath/api.py
- p5/sketch/api.py
Fixes #280 
Each module now has an `api.py` file, which wraps the current p5py functions for processing API support.
> Added Processing API support in p5py

- p5/core/image.py
> Added support for loading images from URLs (fixes #281)

- p5/core/api.py
- p5/sketch/Vispy2DRenderer/renderer2d.py
- p5/sketch/Vispy3DRenderer/renderer3d.py
Closes #296 and other minor updates. 
`push()` was added to Processing that saves current style as well as transformations.
> bug fix : support new APIs to renderer PShape in 3D renderer as well

- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- .github/workflows/sanityTesting.yml
- README.rst
> added badges for workflows

- docs/releasenotes/0.8.0.rst
Related to #360 
Added release notes for v0.8.0
> Add release notes for v0.8.0

- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- .github/workflows/sanityTesting.yml
- docs/releasenotes/index.rst
- p5/__version__.py
- p5/sketch/Skia2DRenderer/base.py
- requirements.txt
- setup.py
Related to #360 
- Update GHAs to support python >= 3.7
- Bump skia to >= 85.0 and update base.py for the new skia version
- Update setup.py
> Upgrading min python version to >= 3.7

- requirements.txt
- urlib needs requests >=2.25.0
> Update requirements.txt for twine

- p5/core/constants.py
- p5/core/font.py
- p5/sketch/Vispy2DRenderer/openglrenderer.py
- p5/sketch/Vispy2DRenderer/renderer2d.py
Refactor `font.py` such that it supports different renderers.
Related to #371
> Refactor font

- docs/reference/environment.rst
- p5/sketch/Skia2DRenderer/base.py
- p5/sketch/Skia2DRenderer/renderer2d.py
- p5/sketch/Vispy2DRenderer/renderer2d.py
- p5/sketch/userspace.py
Small bug fix and added pixel_density.
> Implemented pixel_density for both skia and vispy. Updated the text_wrap in vispy

- p5/sketch/Skia2DRenderer/base.py
> (bug-fix): Anti-aliasing is enabled by default 

- p5/p5types/__init__.py
- p5/pmath/api.py
- p5/pmath/curves.py
- p5/pmath/matrix.py
- p5/pmath/rand.py
- p5/pmath/utils.py
- p5/pmath/vector.py
part of https://github.com/p5py/p5/pull/427
> type pmath module

- docs/install.rst
> Fix minor typos in install.rst

- p5/sketch/events.py
> fix mouse button always set to None in handlers

- .github/workflows/build-tests.yml
- requirements.txt
- setup.py
- Migrate GHAs
- Cleanup requirements.txt
- Update setup.py
> feat: migrate to 3.11
